version: '3.8'

services:
  neo4j-db:
    image: neo4j:latest
    environment:
#      NEO4J_AUTH: 'none'
      NEO4J_AUTH: 'neo4j/YourStrong@Passw0rd'
      apoc.export.file.enabled: 'true'
      apoc.import.file.enabled: 'true'
      apoc.import.file.use_neo4j_config: 'true'
      NEO4J_PLUGINS: '["apoc"]'

    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - nosql_data:/data
      - nosql_logs:/logs

volumes:
  nosql_data:
  nosql_logs:
