version: '3.8'

services:
  carnotes.webapi:
    image: vladimirshvets/carnotes-webapi:1.0.0
    container_name: webapi
    build:
      context: .
      dockerfile: src/Presentation/CarNotes.WebAPI/Dockerfile
    networks:
      - persistence
    depends_on:
      - carnotes.db.neo4j

  carnotes.db.neo4j:
    image: neo4j:5.9.0
    container_name: db-neo4j
    restart: always
    environment:
      # NEO4J_AUTH: 'none'
      NEO4J_AUTH: 'neo4j/YourStrong@Passw0rd'
      NEO4J_PLUGINS: '["apoc"]'
      apoc.export.file.enabled: 'true'
      apoc.import.file.enabled: 'true'
      apoc.import.file.use_neo4j_config: 'true'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - nosql_data:/data
      - nosql_logs:/logs
    networks:
      - persistence

volumes:
  nosql_data:
  nosql_logs:

networks:
  persistence:
    name: persistence
